baseURL = "https://goktenkaradag.com"
languageCode = "tr"
DefaultContentLanguage = "tr"
title = "Gökten Karadağ"  
theme = "anatole"
summarylength = 10
publishDir = "/gktnkrdg.github.io"
# Enable Disqus
#disqusShortname = ""
disableKinds = ["taxonomy", "term"]
# Google Analytics
#googleAnalytics = "UA-149416035-1"

[params]
title = "Gökten Karadağ"
author = "Gökten Karadağ "
description = "Software Developer"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
 mainSections = ["post", "docs"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-2x  fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/g%C3%B6kten/"

[[params.socialIcons]]
icon = "fab fa-2x fa-github"
title = "GitHub"
url = "https://github.com/gktnkrdg"

[[params.socialIcons]]
icon = "fab fa-2x fa-medium"
title = "medium"
url = "https://medium.com/@gktnkrdg"

[[params.socialIcons]]
icon = "fab fa-2x fa-twitter"
title = "twitter"
url = "https://www.twitter.com/gktnkrdg"

[[params.socialIcons]]
icon = "fa fa-2x fa-envelope"
title = "e-mail"
url = "mailto:gktnkrdg@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Anasayfa"
  identifier = "home"
  weight = 100
  url = "/"


 #  [[menu.main]]
 # name = "Hakkımda"
 # weight = 300
 # identifier = "about"
 # url = "/about/"